/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { APEC_CERT_PROGRAM_ADDRESS } from '../programs';

/** CustomError: Custom error message */
export const APEC_CERT_ERROR__CUSTOM_ERROR = 0x1770; // 6000
/** InvalidProof:  */
export const APEC_CERT_ERROR__INVALID_PROOF = 0x1771; // 6001

export type ApecCertError =
  | typeof APEC_CERT_ERROR__CUSTOM_ERROR
  | typeof APEC_CERT_ERROR__INVALID_PROOF;

let apecCertErrorMessages: Record<ApecCertError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  apecCertErrorMessages = {
    [APEC_CERT_ERROR__CUSTOM_ERROR]: `Custom error message`,
    [APEC_CERT_ERROR__INVALID_PROOF]: ``,
  };
}

export function getApecCertErrorMessage(code: ApecCertError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (apecCertErrorMessages as Record<ApecCertError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isApecCertError<TProgramErrorCode extends ApecCertError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    APEC_CERT_PROGRAM_ADDRESS,
    code
  );
}
