/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { APEC_CERT_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CLAIM_CERT_DISCRIMINATOR = new Uint8Array([
  70, 145, 102, 143, 36, 10, 200, 208,
]);

export function getClaimCertDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLAIM_CERT_DISCRIMINATOR);
}

export type ClaimCertInstruction<
  TProgram extends string = typeof APEC_CERT_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountClaimer extends string | AccountMeta<string> = string,
  TAccountProvider extends string | AccountMeta<string> = string,
  TAccountCourse extends string | AccountMeta<string> = string,
  TAccountCertProof extends string | AccountMeta<string> = string,
  TAccountCertMint extends string | AccountMeta<string> = string,
  TAccountClaimerTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends
    | string
    | AccountMeta<string> = 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountClaimer extends string
        ? WritableAccount<TAccountClaimer>
        : TAccountClaimer,
      TAccountProvider extends string
        ? ReadonlyAccount<TAccountProvider>
        : TAccountProvider,
      TAccountCourse extends string
        ? ReadonlyAccount<TAccountCourse>
        : TAccountCourse,
      TAccountCertProof extends string
        ? ReadonlyAccount<TAccountCertProof>
        : TAccountCertProof,
      TAccountCertMint extends string
        ? WritableAccount<TAccountCertMint>
        : TAccountCertMint,
      TAccountClaimerTokenAccount extends string
        ? WritableAccount<TAccountClaimerTokenAccount>
        : TAccountClaimerTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimCertInstructionData = {
  discriminator: ReadonlyUint8Array;
  proof: Array<ReadonlyUint8Array>;
  name: string;
  uri: string;
};

export type ClaimCertInstructionDataArgs = {
  proof: Array<ReadonlyUint8Array>;
  name: string;
  uri: string;
};

export function getClaimCertInstructionDataEncoder(): Encoder<ClaimCertInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['proof', getArrayEncoder(fixEncoderSize(getBytesEncoder(), 32))],
      ['name', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ['uri', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: CLAIM_CERT_DISCRIMINATOR })
  );
}

export function getClaimCertInstructionDataDecoder(): Decoder<ClaimCertInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['proof', getArrayDecoder(fixDecoderSize(getBytesDecoder(), 32))],
    ['name', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['uri', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getClaimCertInstructionDataCodec(): Codec<
  ClaimCertInstructionDataArgs,
  ClaimCertInstructionData
> {
  return combineCodec(
    getClaimCertInstructionDataEncoder(),
    getClaimCertInstructionDataDecoder()
  );
}

export type ClaimCertAsyncInput<
  TAccountPayer extends string = string,
  TAccountClaimer extends string = string,
  TAccountProvider extends string = string,
  TAccountCourse extends string = string,
  TAccountCertProof extends string = string,
  TAccountCertMint extends string = string,
  TAccountClaimerTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  claimer: Address<TAccountClaimer>;
  provider: Address<TAccountProvider>;
  course: Address<TAccountCourse>;
  certProof: Address<TAccountCertProof>;
  certMint: Address<TAccountCertMint>;
  claimerTokenAccount?: Address<TAccountClaimerTokenAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  proof: ClaimCertInstructionDataArgs['proof'];
  name: ClaimCertInstructionDataArgs['name'];
  uri: ClaimCertInstructionDataArgs['uri'];
};

export async function getClaimCertInstructionAsync<
  TAccountPayer extends string,
  TAccountClaimer extends string,
  TAccountProvider extends string,
  TAccountCourse extends string,
  TAccountCertProof extends string,
  TAccountCertMint extends string,
  TAccountClaimerTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof APEC_CERT_PROGRAM_ADDRESS,
>(
  input: ClaimCertAsyncInput<
    TAccountPayer,
    TAccountClaimer,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountCertMint,
    TAccountClaimerTokenAccount,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  ClaimCertInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClaimer,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountCertMint,
    TAccountClaimerTokenAccount,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? APEC_CERT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    claimer: { value: input.claimer ?? null, isWritable: true },
    provider: { value: input.provider ?? null, isWritable: false },
    course: { value: input.course ?? null, isWritable: false },
    certProof: { value: input.certProof ?? null, isWritable: false },
    certMint: { value: input.certMint ?? null, isWritable: true },
    claimerTokenAccount: {
      value: input.claimerTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.claimerTokenAccount.value) {
    accounts.claimerTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.claimer.value)),
        getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
        getAddressEncoder().encode(expectAddress(accounts.certMint.value)),
      ],
    });
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.claimer),
      getAccountMeta(accounts.provider),
      getAccountMeta(accounts.course),
      getAccountMeta(accounts.certProof),
      getAccountMeta(accounts.certMint),
      getAccountMeta(accounts.claimerTokenAccount),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getClaimCertInstructionDataEncoder().encode(
      args as ClaimCertInstructionDataArgs
    ),
    programAddress,
  } as ClaimCertInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClaimer,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountCertMint,
    TAccountClaimerTokenAccount,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type ClaimCertInput<
  TAccountPayer extends string = string,
  TAccountClaimer extends string = string,
  TAccountProvider extends string = string,
  TAccountCourse extends string = string,
  TAccountCertProof extends string = string,
  TAccountCertMint extends string = string,
  TAccountClaimerTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  claimer: Address<TAccountClaimer>;
  provider: Address<TAccountProvider>;
  course: Address<TAccountCourse>;
  certProof: Address<TAccountCertProof>;
  certMint: Address<TAccountCertMint>;
  claimerTokenAccount: Address<TAccountClaimerTokenAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  proof: ClaimCertInstructionDataArgs['proof'];
  name: ClaimCertInstructionDataArgs['name'];
  uri: ClaimCertInstructionDataArgs['uri'];
};

export function getClaimCertInstruction<
  TAccountPayer extends string,
  TAccountClaimer extends string,
  TAccountProvider extends string,
  TAccountCourse extends string,
  TAccountCertProof extends string,
  TAccountCertMint extends string,
  TAccountClaimerTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof APEC_CERT_PROGRAM_ADDRESS,
>(
  input: ClaimCertInput<
    TAccountPayer,
    TAccountClaimer,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountCertMint,
    TAccountClaimerTokenAccount,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): ClaimCertInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountClaimer,
  TAccountProvider,
  TAccountCourse,
  TAccountCertProof,
  TAccountCertMint,
  TAccountClaimerTokenAccount,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? APEC_CERT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    claimer: { value: input.claimer ?? null, isWritable: true },
    provider: { value: input.provider ?? null, isWritable: false },
    course: { value: input.course ?? null, isWritable: false },
    certProof: { value: input.certProof ?? null, isWritable: false },
    certMint: { value: input.certMint ?? null, isWritable: true },
    claimerTokenAccount: {
      value: input.claimerTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.claimer),
      getAccountMeta(accounts.provider),
      getAccountMeta(accounts.course),
      getAccountMeta(accounts.certProof),
      getAccountMeta(accounts.certMint),
      getAccountMeta(accounts.claimerTokenAccount),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getClaimCertInstructionDataEncoder().encode(
      args as ClaimCertInstructionDataArgs
    ),
    programAddress,
  } as ClaimCertInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClaimer,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountCertMint,
    TAccountClaimerTokenAccount,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedClaimCertInstruction<
  TProgram extends string = typeof APEC_CERT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    claimer: TAccountMetas[1];
    provider: TAccountMetas[2];
    course: TAccountMetas[3];
    certProof: TAccountMetas[4];
    certMint: TAccountMetas[5];
    claimerTokenAccount: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    associatedTokenProgram: TAccountMetas[8];
    systemProgram: TAccountMetas[9];
  };
  data: ClaimCertInstructionData;
};

export function parseClaimCertInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedClaimCertInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      claimer: getNextAccount(),
      provider: getNextAccount(),
      course: getNextAccount(),
      certProof: getNextAccount(),
      certMint: getNextAccount(),
      claimerTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getClaimCertInstructionDataDecoder().decode(instruction.data),
  };
}
