/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { APEC_CERT_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CREATE_CERT_PROOF_DISCRIMINATOR = new Uint8Array([
  148, 164, 197, 242, 186, 33, 65, 18,
]);

export function getCreateCertProofDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_CERT_PROOF_DISCRIMINATOR
  );
}

export type CreateCertProofInstruction<
  TProgram extends string = typeof APEC_CERT_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountProvider extends string | AccountMeta<string> = string,
  TAccountCourse extends string | AccountMeta<string> = string,
  TAccountCertProof extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountProvider extends string
        ? ReadonlyAccount<TAccountProvider>
        : TAccountProvider,
      TAccountCourse extends string
        ? ReadonlyAccount<TAccountCourse>
        : TAccountCourse,
      TAccountCertProof extends string
        ? WritableAccount<TAccountCertProof>
        : TAccountCertProof,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateCertProofInstructionData = {
  discriminator: ReadonlyUint8Array;
  root: ReadonlyUint8Array;
  total: bigint;
};

export type CreateCertProofInstructionDataArgs = {
  root: ReadonlyUint8Array;
  total: number | bigint;
};

export function getCreateCertProofInstructionDataEncoder(): FixedSizeEncoder<CreateCertProofInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['root', fixEncoderSize(getBytesEncoder(), 32)],
      ['total', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_CERT_PROOF_DISCRIMINATOR })
  );
}

export function getCreateCertProofInstructionDataDecoder(): FixedSizeDecoder<CreateCertProofInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['root', fixDecoderSize(getBytesDecoder(), 32)],
    ['total', getU64Decoder()],
  ]);
}

export function getCreateCertProofInstructionDataCodec(): FixedSizeCodec<
  CreateCertProofInstructionDataArgs,
  CreateCertProofInstructionData
> {
  return combineCodec(
    getCreateCertProofInstructionDataEncoder(),
    getCreateCertProofInstructionDataDecoder()
  );
}

export type CreateCertProofAsyncInput<
  TAccountAuthority extends string = string,
  TAccountProvider extends string = string,
  TAccountCourse extends string = string,
  TAccountCertProof extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  provider: Address<TAccountProvider>;
  course: Address<TAccountCourse>;
  certProof?: Address<TAccountCertProof>;
  systemProgram?: Address<TAccountSystemProgram>;
  root: CreateCertProofInstructionDataArgs['root'];
  total: CreateCertProofInstructionDataArgs['total'];
};

export async function getCreateCertProofInstructionAsync<
  TAccountAuthority extends string,
  TAccountProvider extends string,
  TAccountCourse extends string,
  TAccountCertProof extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof APEC_CERT_PROGRAM_ADDRESS,
>(
  input: CreateCertProofAsyncInput<
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CreateCertProofInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? APEC_CERT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    provider: { value: input.provider ?? null, isWritable: false },
    course: { value: input.course ?? null, isWritable: false },
    certProof: { value: input.certProof ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.certProof.value) {
    accounts.certProof.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([99, 101, 114, 116, 95, 112, 114, 111, 111, 102])
        ),
        getAddressEncoder().encode(expectAddress(accounts.provider.value)),
        getAddressEncoder().encode(expectAddress(accounts.course.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.provider),
      getAccountMeta(accounts.course),
      getAccountMeta(accounts.certProof),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateCertProofInstructionDataEncoder().encode(
      args as CreateCertProofInstructionDataArgs
    ),
    programAddress,
  } as CreateCertProofInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountSystemProgram
  >);
}

export type CreateCertProofInput<
  TAccountAuthority extends string = string,
  TAccountProvider extends string = string,
  TAccountCourse extends string = string,
  TAccountCertProof extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  provider: Address<TAccountProvider>;
  course: Address<TAccountCourse>;
  certProof: Address<TAccountCertProof>;
  systemProgram?: Address<TAccountSystemProgram>;
  root: CreateCertProofInstructionDataArgs['root'];
  total: CreateCertProofInstructionDataArgs['total'];
};

export function getCreateCertProofInstruction<
  TAccountAuthority extends string,
  TAccountProvider extends string,
  TAccountCourse extends string,
  TAccountCertProof extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof APEC_CERT_PROGRAM_ADDRESS,
>(
  input: CreateCertProofInput<
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CreateCertProofInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountProvider,
  TAccountCourse,
  TAccountCertProof,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? APEC_CERT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    provider: { value: input.provider ?? null, isWritable: false },
    course: { value: input.course ?? null, isWritable: false },
    certProof: { value: input.certProof ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.provider),
      getAccountMeta(accounts.course),
      getAccountMeta(accounts.certProof),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateCertProofInstructionDataEncoder().encode(
      args as CreateCertProofInstructionDataArgs
    ),
    programAddress,
  } as CreateCertProofInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountCertProof,
    TAccountSystemProgram
  >);
}

export type ParsedCreateCertProofInstruction<
  TProgram extends string = typeof APEC_CERT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    provider: TAccountMetas[1];
    course: TAccountMetas[2];
    certProof: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: CreateCertProofInstructionData;
};

export function parseCreateCertProofInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateCertProofInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      provider: getNextAccount(),
      course: getNextAccount(),
      certProof: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateCertProofInstructionDataDecoder().decode(instruction.data),
  };
}
