/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { APEC_CERT_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CREATE_COURSE_DISCRIMINATOR = new Uint8Array([
  120, 121, 154, 164, 107, 180, 167, 241,
]);

export function getCreateCourseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_COURSE_DISCRIMINATOR
  );
}

export type CreateCourseInstruction<
  TProgram extends string = typeof APEC_CERT_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountProvider extends string | AccountMeta<string> = string,
  TAccountCourse extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountProvider extends string
        ? ReadonlyAccount<TAccountProvider>
        : TAccountProvider,
      TAccountCourse extends string
        ? WritableAccount<TAccountCourse>
        : TAccountCourse,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateCourseInstructionData = {
  discriminator: ReadonlyUint8Array;
  id: bigint;
  shortName: string;
};

export type CreateCourseInstructionDataArgs = {
  id: number | bigint;
  shortName: string;
};

export function getCreateCourseInstructionDataEncoder(): Encoder<CreateCourseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['id', getU64Encoder()],
      ['shortName', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: CREATE_COURSE_DISCRIMINATOR })
  );
}

export function getCreateCourseInstructionDataDecoder(): Decoder<CreateCourseInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['id', getU64Decoder()],
    ['shortName', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getCreateCourseInstructionDataCodec(): Codec<
  CreateCourseInstructionDataArgs,
  CreateCourseInstructionData
> {
  return combineCodec(
    getCreateCourseInstructionDataEncoder(),
    getCreateCourseInstructionDataDecoder()
  );
}

export type CreateCourseAsyncInput<
  TAccountAuthority extends string = string,
  TAccountProvider extends string = string,
  TAccountCourse extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  provider: Address<TAccountProvider>;
  course?: Address<TAccountCourse>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: CreateCourseInstructionDataArgs['id'];
  shortName: CreateCourseInstructionDataArgs['shortName'];
};

export async function getCreateCourseInstructionAsync<
  TAccountAuthority extends string,
  TAccountProvider extends string,
  TAccountCourse extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof APEC_CERT_PROGRAM_ADDRESS,
>(
  input: CreateCourseAsyncInput<
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CreateCourseInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? APEC_CERT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    provider: { value: input.provider ?? null, isWritable: false },
    course: { value: input.course ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.course.value) {
    accounts.course.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 117, 114, 115, 101])),
        getAddressEncoder().encode(expectAddress(accounts.provider.value)),
        getU64Encoder().encode(expectSome(args.id)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.provider),
      getAccountMeta(accounts.course),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateCourseInstructionDataEncoder().encode(
      args as CreateCourseInstructionDataArgs
    ),
    programAddress,
  } as CreateCourseInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountSystemProgram
  >);
}

export type CreateCourseInput<
  TAccountAuthority extends string = string,
  TAccountProvider extends string = string,
  TAccountCourse extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  provider: Address<TAccountProvider>;
  course: Address<TAccountCourse>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: CreateCourseInstructionDataArgs['id'];
  shortName: CreateCourseInstructionDataArgs['shortName'];
};

export function getCreateCourseInstruction<
  TAccountAuthority extends string,
  TAccountProvider extends string,
  TAccountCourse extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof APEC_CERT_PROGRAM_ADDRESS,
>(
  input: CreateCourseInput<
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CreateCourseInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountProvider,
  TAccountCourse,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? APEC_CERT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    provider: { value: input.provider ?? null, isWritable: false },
    course: { value: input.course ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.provider),
      getAccountMeta(accounts.course),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateCourseInstructionDataEncoder().encode(
      args as CreateCourseInstructionDataArgs
    ),
    programAddress,
  } as CreateCourseInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProvider,
    TAccountCourse,
    TAccountSystemProgram
  >);
}

export type ParsedCreateCourseInstruction<
  TProgram extends string = typeof APEC_CERT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    provider: TAccountMetas[1];
    course: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: CreateCourseInstructionData;
};

export function parseCreateCourseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateCourseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      provider: getNextAccount(),
      course: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateCourseInstructionDataDecoder().decode(instruction.data),
  };
}
