/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { APEC_CERT_PROGRAM_ADDRESS } from '../programs';
import {
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const INIT_PROVIDER_DISCRIMINATOR = new Uint8Array([
  118, 169, 91, 206, 83, 110, 185, 107,
]);

export function getInitProviderDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_PROVIDER_DISCRIMINATOR
  );
}

export type InitProviderInstruction<
  TProgram extends string = typeof APEC_CERT_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountProvider extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountProvider extends string
        ? WritableAccount<TAccountProvider>
        : TAccountProvider,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitProviderInstructionData = {
  discriminator: ReadonlyUint8Array;
  id: bigint;
  shortName: string;
};

export type InitProviderInstructionDataArgs = {
  id: number | bigint;
  shortName: string;
};

export function getInitProviderInstructionDataEncoder(): Encoder<InitProviderInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['id', getU64Encoder()],
      ['shortName', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: INIT_PROVIDER_DISCRIMINATOR })
  );
}

export function getInitProviderInstructionDataDecoder(): Decoder<InitProviderInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['id', getU64Decoder()],
    ['shortName', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getInitProviderInstructionDataCodec(): Codec<
  InitProviderInstructionDataArgs,
  InitProviderInstructionData
> {
  return combineCodec(
    getInitProviderInstructionDataEncoder(),
    getInitProviderInstructionDataDecoder()
  );
}

export type InitProviderAsyncInput<
  TAccountAuthority extends string = string,
  TAccountProvider extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  provider?: Address<TAccountProvider>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: InitProviderInstructionDataArgs['id'];
  shortName: InitProviderInstructionDataArgs['shortName'];
};

export async function getInitProviderInstructionAsync<
  TAccountAuthority extends string,
  TAccountProvider extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof APEC_CERT_PROGRAM_ADDRESS,
>(
  input: InitProviderAsyncInput<
    TAccountAuthority,
    TAccountProvider,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitProviderInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProvider,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? APEC_CERT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    provider: { value: input.provider ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.provider.value) {
    accounts.provider.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([112, 114, 111, 118, 105, 100, 101, 114])
        ),
        getU64Encoder().encode(expectSome(args.id)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.provider),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitProviderInstructionDataEncoder().encode(
      args as InitProviderInstructionDataArgs
    ),
    programAddress,
  } as InitProviderInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProvider,
    TAccountSystemProgram
  >);
}

export type InitProviderInput<
  TAccountAuthority extends string = string,
  TAccountProvider extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  provider: Address<TAccountProvider>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: InitProviderInstructionDataArgs['id'];
  shortName: InitProviderInstructionDataArgs['shortName'];
};

export function getInitProviderInstruction<
  TAccountAuthority extends string,
  TAccountProvider extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof APEC_CERT_PROGRAM_ADDRESS,
>(
  input: InitProviderInput<
    TAccountAuthority,
    TAccountProvider,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitProviderInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountProvider,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? APEC_CERT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    provider: { value: input.provider ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.provider),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitProviderInstructionDataEncoder().encode(
      args as InitProviderInstructionDataArgs
    ),
    programAddress,
  } as InitProviderInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProvider,
    TAccountSystemProgram
  >);
}

export type ParsedInitProviderInstruction<
  TProgram extends string = typeof APEC_CERT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    provider: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: InitProviderInstructionData;
};

export function parseInitProviderInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitProviderInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      provider: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitProviderInstructionDataDecoder().decode(instruction.data),
  };
}
