/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const CERT_PROOF_DISCRIMINATOR = new Uint8Array([
  82, 4, 192, 74, 105, 190, 230, 170,
]);

export function getCertProofDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CERT_PROOF_DISCRIMINATOR);
}

export type CertProof = {
  discriminator: ReadonlyUint8Array;
  provider: Address;
  course: Address;
  root: ReadonlyUint8Array;
  total: bigint;
  claimed: bigint;
  bump: number;
};

export type CertProofArgs = {
  provider: Address;
  course: Address;
  root: ReadonlyUint8Array;
  total: number | bigint;
  claimed: number | bigint;
  bump: number;
};

export function getCertProofEncoder(): FixedSizeEncoder<CertProofArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['provider', getAddressEncoder()],
      ['course', getAddressEncoder()],
      ['root', fixEncoderSize(getBytesEncoder(), 32)],
      ['total', getU64Encoder()],
      ['claimed', getU64Encoder()],
      ['bump', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CERT_PROOF_DISCRIMINATOR })
  );
}

export function getCertProofDecoder(): FixedSizeDecoder<CertProof> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['provider', getAddressDecoder()],
    ['course', getAddressDecoder()],
    ['root', fixDecoderSize(getBytesDecoder(), 32)],
    ['total', getU64Decoder()],
    ['claimed', getU64Decoder()],
    ['bump', getU8Decoder()],
  ]);
}

export function getCertProofCodec(): FixedSizeCodec<CertProofArgs, CertProof> {
  return combineCodec(getCertProofEncoder(), getCertProofDecoder());
}

export function decodeCertProof<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<CertProof, TAddress>;
export function decodeCertProof<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<CertProof, TAddress>;
export function decodeCertProof<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<CertProof, TAddress> | MaybeAccount<CertProof, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getCertProofDecoder()
  );
}

export async function fetchCertProof<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<CertProof, TAddress>> {
  const maybeAccount = await fetchMaybeCertProof(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeCertProof<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<CertProof, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeCertProof(maybeAccount);
}

export async function fetchAllCertProof(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<CertProof>[]> {
  const maybeAccounts = await fetchAllMaybeCertProof(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeCertProof(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<CertProof>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeCertProof(maybeAccount));
}

export function getCertProofSize(): number {
  return 121;
}
