/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const PROVIDER_DISCRIMINATOR = new Uint8Array([
  164, 180, 71, 17, 75, 216, 80, 195,
]);

export function getProviderDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(PROVIDER_DISCRIMINATOR);
}

export type Provider = {
  discriminator: ReadonlyUint8Array;
  id: bigint;
  authority: Address;
  bump: number;
  shortName: string;
};

export type ProviderArgs = {
  id: number | bigint;
  authority: Address;
  bump: number;
  shortName: string;
};

export function getProviderEncoder(): Encoder<ProviderArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['id', getU64Encoder()],
      ['authority', getAddressEncoder()],
      ['bump', getU8Encoder()],
      ['shortName', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: PROVIDER_DISCRIMINATOR })
  );
}

export function getProviderDecoder(): Decoder<Provider> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['id', getU64Decoder()],
    ['authority', getAddressDecoder()],
    ['bump', getU8Decoder()],
    ['shortName', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getProviderCodec(): Codec<ProviderArgs, Provider> {
  return combineCodec(getProviderEncoder(), getProviderDecoder());
}

export function decodeProvider<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Provider, TAddress>;
export function decodeProvider<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Provider, TAddress>;
export function decodeProvider<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Provider, TAddress> | MaybeAccount<Provider, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getProviderDecoder()
  );
}

export async function fetchProvider<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Provider, TAddress>> {
  const maybeAccount = await fetchMaybeProvider(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeProvider<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Provider, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeProvider(maybeAccount);
}

export async function fetchAllProvider(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Provider>[]> {
  const maybeAccounts = await fetchAllMaybeProvider(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeProvider(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Provider>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeProvider(maybeAccount));
}
